2024-08-08 20:51:34,951	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 20:51:35,220	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 5242
2024-08-08 20:51:35,773	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 20:51:35,773	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 20:51:35,773	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 20:51:35,774	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 20:51:36,019	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 20:51:36,158	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 20:51:36,159	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 20:53:14,156	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 20:53:14,392	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 5143
2024-08-08 20:53:14,954	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 20:53:14,954	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 20:53:14,954	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 20:53:14,954	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 20:53:15,152	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 20:53:15,291	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 20:53:15,291	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 20:54:34,260	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 20:54:34,449	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 5063
2024-08-08 20:54:34,984	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 20:54:34,984	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 20:54:34,984	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 20:54:34,984	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 20:54:35,205	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 20:54:35,326	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 20:54:35,326	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 20:59:26,402	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 20:59:26,616	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 4771
2024-08-08 20:59:27,142	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 20:59:27,143	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 20:59:27,143	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 20:59:27,143	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 20:59:27,357	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 20:59:27,473	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 20:59:27,473	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 21:02:18,143	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 21:02:18,385	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 4599
2024-08-08 21:02:19,030	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 21:02:19,030	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:02:19,030	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:02:19,031	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:02:19,261	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:02:19,395	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 21:02:19,395	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 21:03:49,594	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 21:03:49,829	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 4508
2024-08-08 21:03:50,388	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 21:03:50,388	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:03:50,388	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:03:50,388	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:03:50,684	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:03:50,850	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 21:03:50,850	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 21:06:17,178	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 21:06:17,408	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 4360
2024-08-08 21:06:18,096	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 21:06:18,096	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:06:18,096	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:06:18,096	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:06:18,493	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:06:18,612	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 21:06:18,612	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 21:09:07,456	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 21:09:07,729	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 4190
2024-08-08 21:09:08,327	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 21:09:08,327	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:09:08,327	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:09:08,327	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:09:08,639	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:09:08,744	[INFO]	(gateway.py:56)on_closed	[botpy] 关闭, 返回码: 4014, 返回信息: disallowed intents
2024-08-08 21:09:08,744	[INFO]	(gateway.py:62)on_closed	[botpy] 无法重连，创建新连接!
2024-08-08 21:09:08,744	[INFO]	(gateway.py:134)ws_connect	[botpy] ws关闭, 停止接收消息!
2024-08-08 21:09:13,763	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:09:13,763	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:09:13,763	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:09:14,037	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:09:14,148	[INFO]	(gateway.py:56)on_closed	[botpy] 关闭, 返回码: 4014, 返回信息: disallowed intents
2024-08-08 21:09:14,148	[INFO]	(gateway.py:62)on_closed	[botpy] 无法重连，创建新连接!
2024-08-08 21:09:14,148	[INFO]	(gateway.py:134)ws_connect	[botpy] ws关闭, 停止接收消息!
2024-08-08 21:09:27,753	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 21:09:27,978	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 4169
2024-08-08 21:09:28,505	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 21:09:28,505	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:09:28,505	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:09:28,505	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:09:28,720	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:09:28,838	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 21:09:28,839	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 21:35:03,277	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 21:35:03,537	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 2634
2024-08-08 21:35:04,058	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 21:35:04,058	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 21:35:04,059	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 21:35:04,059	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 21:35:04,379	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 21:35:04,504	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 21:35:04,504	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:01:10,847	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:01:11,074	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 1066
2024-08-08 22:01:11,836	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:01:11,837	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:01:11,837	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:01:11,837	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:01:12,033	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:01:12,201	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:01:12,202	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:01:17,616	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4A735DE68F8C64698BCAA35CC1E198D5/files, 错误代码: 400, 返回内容: {'message': '请求参数url无效', 'code': 850028, 'err_code': 40011021, 'trace_id': '4819988c9a1b4c700f7a8ca8faef77b8'}, trace_id:4819988c9a1b4c700f7a8ca8faef77b8
2024-08-08 22:06:59,354	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:06:59,956	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 717
2024-08-08 22:07:00,537	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:07:00,538	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:07:00,538	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:07:00,538	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:07:00,759	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:07:00,907	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:07:00,907	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:07:04,335	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4A735DE68F8C64698BCAA35CC1E198D5/files, 错误代码: 400, 返回内容: {'message': '富媒体文件下载失败', 'code': 850026, 'err_code': 40034001, 'trace_id': '4eafd49c8d8cd012e0a99a9487ff90b7'}, trace_id:4eafd49c8d8cd012e0a99a9487ff90b7
2024-08-08 22:07:39,670	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4A735DE68F8C64698BCAA35CC1E198D5/files, 错误代码: 400, 返回内容: {'message': '富媒体文件下载失败', 'code': 850026, 'err_code': 40034001, 'trace_id': '598f5b3f9f9cac25712cdd34f2baf9b8'}, trace_id:598f5b3f9f9cac25712cdd34f2baf9b8
2024-08-08 22:09:31,545	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4A735DE68F8C64698BCAA35CC1E198D5/files, 错误代码: 400, 返回内容: {'message': '富媒体文件下载失败', 'code': 850026, 'err_code': 40034001, 'trace_id': 'd5963b33e98a4cc1c7fbcb5e8b1a4319'}, trace_id:d5963b33e98a4cc1c7fbcb5e8b1a4319
2024-08-08 22:11:31,576	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:11:31,825	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 445
2024-08-08 22:11:32,381	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:11:32,381	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:11:32,381	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:11:32,381	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:11:32,638	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:11:32,770	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:11:32,770	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:12:04,393	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:12:04,672	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 413
2024-08-08 22:12:05,311	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:12:05,312	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:12:05,312	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:12:05,312	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:12:05,499	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:12:05,595	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:12:05,596	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:12:51,307	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:12:51,589	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 366
2024-08-08 22:12:52,157	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:12:52,158	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:12:52,158	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:12:52,158	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:12:52,365	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:12:52,487	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:12:52,487	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:12:55,759	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4A735DE68F8C64698BCAA35CC1E198D5/files, 错误代码: 400, 返回内容: {'message': '请求参数url无效', 'code': 850028, 'err_code': 40011021, 'trace_id': 'b441f72364e6220098e425438cd21225'}, trace_id:b441f72364e6220098e425438cd21225
2024-08-08 22:45:41,794	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:45:42,056	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 7200
2024-08-08 22:45:42,582	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:45:42,582	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:45:42,582	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:45:42,582	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:45:42,816	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:45:42,954	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:45:42,954	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:47:16,211	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:47:16,780	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 7106
2024-08-08 22:47:17,295	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:47:17,296	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:47:17,296	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:47:17,296	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:47:17,980	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:47:18,121	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:47:18,121	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
2024-08-08 22:47:22,839	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4DD3B06D4B52321273E73D57DE5C59EE/files, 错误代码: 400, 返回内容: {'message': '富媒体文件下载失败', 'code': 850026, 'err_code': 40034001, 'trace_id': 'fe642f65fdd732e12ae2beba1b7b6848'}, trace_id:fe642f65fdd732e12ae2beba1b7b6848
2024-08-08 22:47:35,298	[ERROR]	(http.py:76)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/v2/groups/4DD3B06D4B52321273E73D57DE5C59EE/files, 错误代码: 400, 返回内容: {'message': '富媒体文件下载失败', 'code': 850026, 'err_code': 40034001, 'trace_id': '95671022f06cfc00ffdfc3b6f51a42cf'}, trace_id:95671022f06cfc00ffdfc3b6f51a42cf
2024-08-08 22:48:17,769	[INFO]	(client.py:162)_bot_login	[botpy] 登录机器人账号中...
2024-08-08 22:48:18,013	[INFO]	(robot.py:65)update_access_token	[botpy] access_token expires_in 7044
2024-08-08 22:48:18,574	[INFO]	(client.py:181)_bot_init	[botpy] 程序启动...
2024-08-08 22:48:18,575	[INFO]	(connection.py:60)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-08 22:48:18,575	[INFO]	(client.py:242)bot_connect	[botpy] 会话启动中...
2024-08-08 22:48:18,575	[INFO]	(gateway.py:115)ws_connect	[botpy] 启动中...
2024-08-08 22:48:18,770	[INFO]	(gateway.py:142)ws_identify	[botpy] 鉴权中...
2024-08-08 22:48:18,899	[INFO]	(gateway.py:85)on_message	[botpy] 机器人「ShikanokoBOT」启动成功！
2024-08-08 22:48:18,899	[INFO]	(gateway.py:223)_send_heart	[botpy] 心跳维持启动...
